sonar.projectKey=Nathanmar_TP3-CICD
sonar.organization=nathanmar
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,jest.config.js,playwright.config.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
